### PR TITLE
Add legal link and dialog

### PR DESCRIPTION
**Pull request by thisismydesign**
image

image

### CODE REVIEW

**Comment by Kexort** [comment]
Preview available here: https://s3.eu-central-1.amazonaws.com/kexort/issue-42_add-legal/index.html

**Review by Kexort — APPROVED** [review]

**Comment by thisismydesign** [comment]
Wanted to interpolate a link to `contact us` but I'm kinda lost. @Kexort?

**Comment by thisismydesign** [comment]
Also fixed style issue with vertical separator

image

**Comment by thisismydesign** [comment]
@Kexort one more review pls and then i'd merge

**Comment by thisismydesign** [comment]
Resolves #42

**Review by Kexort — APPROVED** [review]

**Pull request merged**
