### PR TITLE
Remove vertical scroll

### PR DESCRIPTION
**Pull request by thisismydesign**
There's a small vertical scroll on windows OS, this removes it. Might be caused by body width 100%. There might be a better solution.

### CODE REVIEW

**Comment by Kexort** [comment]
Preview available here: https://s3.eu-central-1.amazonaws.com/kexort/remove-verticall-scroll/index.html

**Comment by thisismydesign** [comment]
@Kexort I actually prefer this solution to a random hardcoded width. Why would that be superior?

**Comment by Kexort** [comment]
@thisismydesign I never said that setting min-width is a superior solution, I just mentioned that as a _possible_ solution.

**Comment by Kexort** [comment]
I checked it on Windows at fullHD and I'm **NOT OK** with the current look.

image
Removing width: 100% from body gives us this:
image
I think this looks better. If you fix it go ahead with the merge.
Thanks!

**Pull request merged**
