### PR TITLE
Fix relic IDs

### LINKED ISSUE #53: Fix The Taming and Skin of the Loyal id
The Taming and Skin of the Loyal has the same id

### PR DESCRIPTION
**Pull request by Kexort**
Fixes #53

### CODE REVIEW

**Comment by Kexort** [comment]
Preview available here: https://s3.eu-central-1.amazonaws.com/kexort/fix_relics_json/index.html

**Comment by thisismydesign** [comment]
Why? I suggest not keeping track of relic IDs as long as they are unique. We already removed/ added some so it's not continuous.

**Comment by Kexort** [comment]
Because there were NOT unique

> The Taming and Skin of the Loyal has the same id

**Review by thisismydesign — APPROVED** [review]
Very good find then, missed the issue, sorry :)

**Pull request merged**
