### PR TITLE
Remove checkbox from rows

### PR DESCRIPTION
**Pull request by Kexort**

### CODE REVIEW

**Comment by Kexort** [comment]
Preview available here: https://s3.eu-central-1.amazonaws.com/kexort/remove_checkbox/index.html

**Comment by Kexort** [comment]
Part of #49

**Comment by thisismydesign** [comment]
I would add a hovering animation to make it more intuitive that they are clickable. Or perhaps a tick sign with a hovering animation instead of a checkbox.

**Review by thisismydesign — COMMENTED** [review]
LGTM so far, I'd make the hover color a bit more sallow / opaque.

**Pull request merged**
